### ISSUE TITLE
building feature/kotlin_rewrite

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1011]
Can I build the feature/kotlin_rewrite without having to build the linphone-sdk first?

I tried the following after checking out the branch:

```bash
$ ./gradlew installDebug

> Configure project :app
Git version: 4.3-alpha.77+638553c1a

FAILURE: Build failed with an exception.

* Where:
Build file '/home/brian/linphone-android/app/build.gradle' line: 128

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'LinphoneSdkBuildDir' for object of type org.gradle.api.internal.artifacts.repositories.DefaultMavenArtifactRepository.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

which I think is telling me it's looking for the linphone-sdk build dir, instead of downloading the AAR, isn't it?

**Comment by brianjmurrell** [comment]
I did find https://github.com/BelledonneCommunications/linphone-android/blob/638553c1ad551c404072aea1a015f2b5674c28e2/app/build.gradle#L127-L133

But now I am getting:

```
$ ./gradlew installDebug

> Configure project :app
Git version: 4.3-alpha.77+638553c1a

> Task :app:compileDebugKotlin FAILED
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (110, 9): 'onAudioDeviceChanged' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (110, 68): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (115, 9): 'onAudioDevicesListUpdated' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (157, 44): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (158, 34): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (246, 46): Unresolved reference: audioDevices
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (247, 37): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (249, 34): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (258, 46): Unresolved reference: audioDevices
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (259, 37): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (261, 34): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (270, 46): Unresolved reference: audioDevices
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (271, 38): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (271, 95): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (273, 34): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (300, 44): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (301, 56): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (306, 46): Unresolved reference: audioDevices
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (307, 37): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (319, 44): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (320, 65): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/fragments/AdvancedSettingsFragment.kt: (39, 32): Unresolved reference: compatibility
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/fragments/AdvancedSettingsFragment.kt: (79, 50): Unresolved reference: DeviceUtils
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (26, 26): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (92, 22): Unresolved reference: defaultOutputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (98, 69): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (186, 34): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (187, 34): Unresolved reference: audioDevices
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (188, 43): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (196, 28): Unresolved reference: defaultOutputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/NetworkSettingsViewModel.kt: (42, 18): Unresolved reference: isPushNotificationEnabled
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/NetworkSettingsViewModel.kt: (67, 40): Unresolved reference: isPushNotificationEnabled
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (26, 32): Unresolved reference: service
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (28, 21): There's a cycle in the inheritance hierarchy for this type
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (28, 21): This type is final, so it cannot be inherited from
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (29, 5): 'onCreate' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (30, 15): Unresolved reference: onCreate
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (36, 5): 'onStartCommand' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (43, 22): Unresolved reference: onStartCommand
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (46, 5): 'createServiceNotificationChannel' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (50, 5): 'showForegroundServiceNotification' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (54, 5): 'hideForegroundServiceNotification' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (58, 5): 'onTaskRemoved' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (64, 15): Unresolved reference: onTaskRemoved
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (67, 5): 'onDestroy' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (71, 15): Unresolved reference: onDestroy
e: /home/brian/linphone-android/app/src/main/java/org/linphone/notifications/NotificationsManager.kt: (276, 21): Unresolved reference: startForeground
e: /home/brian/linphone-android/app/src/main/java/org/linphone/notifications/NotificationsManager.kt: (284, 22): Unresolved reference: startForeground
e: /home/brian/linphone-android/app/src/main/java/org/linphone/notifications/NotificationsManager.kt: (291, 22): Unresolved reference: stopForeground

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
21 actionable tasks: 1 executed, 20 up-to-date
```

**Comment by Viish** [comment]
Indeed the online maven repository was commented out because it required a SDK that wasn't available online, but this is no longer the case so I just pushed a commit to add back the online maven repository so you can try again.
Also for the `LinphoneSdkBuildDir` take a look at the README.
Finally your build issue happens because you don't have the right SDK.

**Comment by brianjmurrell** [comment]
OK.  Updated to decbee224 and nuked `~/.gradle/caches` but still getting:

```
$ ./gradlew installDebug

> Configure project :app
Git version: 4.3-alpha.80+decbee224

> Task :app:stripDebugDebugSymbols UP-TO-DATE
WARNING: Compatible side by side NDK version was not found. Default is 20.0.5594570.
Compatible side by side NDK version was not found. Default is 20.0.5594570.

> Task :app:compileDebugKotlin FAILED
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (110, 9): 'onAudioDeviceChanged' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (110, 68): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (115, 9): 'onAudioDevicesListUpdated' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (157, 44): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (158, 34): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (246, 46): Unresolved reference: audioDevices
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (247, 37): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (249, 34): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (258, 46): Unresolved reference: audioDevices
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (259, 37): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (261, 34): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (270, 46): Unresolved reference: audioDevices
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (271, 38): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (271, 95): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (273, 34): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (300, 44): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (301, 56): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (306, 46): Unresolved reference: audioDevices
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (307, 37): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (319, 44): Unresolved reference: outputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/call/viewmodels/ControlsViewModel.kt: (320, 65): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/fragments/AdvancedSettingsFragment.kt: (39, 32): Unresolved reference: compatibility
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/fragments/AdvancedSettingsFragment.kt: (79, 50): Unresolved reference: DeviceUtils
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (26, 26): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (92, 22): Unresolved reference: defaultOutputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (98, 69): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (186, 34): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (187, 34): Unresolved reference: audioDevices
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (188, 43): Unresolved reference: AudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.kt: (196, 28): Unresolved reference: defaultOutputAudioDevice
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/NetworkSettingsViewModel.kt: (42, 18): Unresolved reference: isPushNotificationEnabled
e: /home/brian/linphone-android/app/src/main/java/org/linphone/activities/main/settings/viewmodels/NetworkSettingsViewModel.kt: (67, 40): Unresolved reference: isPushNotificationEnabled
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (26, 32): Unresolved reference: service
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (28, 21): There's a cycle in the inheritance hierarchy for this type
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (28, 21): This type is final, so it cannot be inherited from
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (29, 5): 'onCreate' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (30, 15): Unresolved reference: onCreate
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (36, 5): 'onStartCommand' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (43, 22): Unresolved reference: onStartCommand
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (46, 5): 'createServiceNotificationChannel' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (50, 5): 'showForegroundServiceNotification' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (54, 5): 'hideForegroundServiceNotification' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (58, 5): 'onTaskRemoved' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (64, 15): Unresolved reference: onTaskRemoved
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (67, 5): 'onDestroy' overrides nothing
e: /home/brian/linphone-android/app/src/main/java/org/linphone/core/CoreService.kt: (71, 15): Unresolved reference: onDestroy
e: /home/brian/linphone-android/app/src/main/java/org/linphone/notifications/NotificationsManager.kt: (276, 21): Unresolved reference: startForeground
e: /home/brian/linphone-android/app/src/main/java/org/linphone/notifications/NotificationsManager.kt: (284, 22): Unresolved reference: startForeground
e: /home/brian/linphone-android/app/src/main/java/org/linphone/notifications/NotificationsManager.kt: (291, 22): Unresolved reference: stopForeground

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 55s
31 actionable tasks: 2 executed, 29 up-to-date
```

**Comment by Viish** [comment]
Yes we have an issue with our pipeline that generates and uploads AARs to our maven repository, the latest AAR isn't available yet.

**Comment by brianjmurrell** [comment]
Any ETA on when that will be resolved?  Just so that I can decide how I'm going forward.

**Comment by Viish** [comment]
I'm working on it since this morning, hopefully it will be fixed by the end of the day.
In the meantime you can build the SDK yourself.

**Comment by brianjmurrell** [comment]
Yeah, I've tried building the SDK myself numerous times.  I don't think I have ever succeeded.

**Comment by Viish** [comment]
You can use this one: https://linphone.org/maven_repository/org/linphone/linphone-sdk-android/4.4.0-alpha.240+9056a7d/linphone-sdk-android-4.4.0-alpha.240+9056a7d.aar

**Comment by Viish** [comment]
Should be fixed now.

**Comment by brianjmurrell** [comment]
```
$ ./gradlew installDebug

> Configure project :app
Git version: 4.3-alpha.80+decbee224

> Task :app:stripDebugDebugSymbols UP-TO-DATE
WARNING: Compatible side by side NDK version was not found. Default is 20.0.5594570.
Compatible side by side NDK version was not found. Default is 20.0.5594570.

> Task :app:kaptDebugKotlin FAILED
/home/brian/linphone-android/app/build/tmp/kapt3/stubs/debug/org/linphone/activities/main/settings/viewmodels/AudioSettingsViewModel.java:36: error: cannot find symbol
    private final androidx.lifecycle.MutableLiveData<java.util.ArrayList<org.linphone.core.AudioDevice>> outputAudioDeviceValues = null;
                                                                                          ^
  symbol:   class AudioDevice
  location: package org.linphone.core
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 25s
30 actionable tasks: 6 executed, 24 up-to-date
$ ls -l /home/brian/.gradle/caches/modules-2/files-2.1/org.linphone/linphone-sdk-android/4.4.0-alpha.226+c4ecb1a/2bffa2c3679eeb414a813860d9d96e2a5d75924a
total 37588
-rw-rw-r--. 1 brian brian 38482381 May 15 10:43 linphone-sdk-android-4.4.0-alpha.226+c4ecb1a.aar
```

**Comment by Viish** [comment]
First of all, pull my latest commit to ensure it will take a 4.4.0-alpha version (4.4+ will take a beta version now but it isn't compatible with kotlin branch).
Also, do a `./gradlew build --refresh-dependencies` to ensure the maven repository informations are up to date.
Finally, start the build again.

**Comment by brianjmurrell** [comment]
```
$ git show
commit 2fdac54a136616b8135debae0613f4208b26fc92 (HEAD -> my_firebase_kotlin, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Fri May 15 16:39:26 2020 +0200

    Updated build.gradle for force use 4.4.0-alpha and not 4.4.0-beta

diff --git a/app/build.gradle b/app/build.gradle
index ad92efabd..8e83ba468 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -153,7 +153,7 @@ dependencies {
         implementation 'com.google.firebase:firebase-messaging:19.0.1'
     }
 
-    implementation 'org.linphone:linphone-sdk-android:4.4+'
+    implementation 'org.linphone:linphone-sdk-android:4.4.0-alpha+'
 }
 
 if (firebaseEnabled()) {
$ ./gradlew build --refresh-dependencies

> Configure project :app
Git version: 4.3-alpha.81+2fdac54a1

> Task :app:stripDebugDebugSymbols UP-TO-DATE
WARNING: Compatible side by side NDK version was not found. Default is 20.0.5594570.
Compatible side by side NDK version was not found. Default is 20.0.5594570.

> Task :app:stripReleaseDebugSymbols
Unable to strip the following libraries, packaging them as they are: libbctoolbox-tester.so, libbctoolbox-tester.so, libbctoolbox-tester.so, libbctoolbox-tester.so, libbctoolbox.so, libbctoolbox.so, libbctoolbox.so, libbctoolbox.so, libc++_shared.so, libc++_shared.so, libc++_shared.so, libc++_shared.so, liblinphone.so, liblinphone.so, liblinphone.so, liblinphone.so, liblinphonetester.so, liblinphonetester.so, liblinphonetester.so, liblinphonetester.so, libmediastreamer.so, libmediastreamer.so, libmediastreamer.so, libmediastreamer.so, libmsandroidcamera2.so, libmsandroidcamera2.so, libmsandroidcamera2.so, libmsandroidcamera2.so, libmswebrtc.so, libmswebrtc.so, libmswebrtc.so, libmswebrtc.so, libortp.so, libortp.so, libortp.so, libortp.so.

> Task :app:validateSigningRelease FAILED

> Task :app:kaptDebugKotlin
/home/brian/linphone-android/app/build/generated/source/kapt/debug/org/linphone/DataBinderMapperImpl.java:71: error: cannot find symbol
import org.linphone.databinding.ChatRoomMasterFragmentBindingImpl;
                               ^
  symbol:   class ChatRoomMasterFragmentBindingImpl
  location: package org.linphone.databinding/home/brian/linphone-android/app/build/generated/source/kapt/debug/org/linphone/DataBinderMapperImpl.java:72: error: cannot find symbol
import org.linphone.databinding.ChatRoomMasterFragmentBindingLandImpl;
                               ^
  symbol:   class ChatRoomMasterFragmentBindingLandImpl
  location: package org.linphone.databinding/home/brian/linphone-android/app/build/generated/source/kapt/debug/org/linphone/DataBinderMapperImpl.java:73: error: cannot find symbol
import org.linphone.databinding.ChatRoomMasterFragmentBindingSw533dpLandImpl;
                               ^
  symbol:   class ChatRoomMasterFragmentBindingSw533dpLandImpl
  location: package org.linphone.databinding/home/brian/linphone-android/app/build/generated/source/kapt/debug/org/linphone/DataBinderMapperImpl.java:113: error: cannot find symbol
import org.linphone.databinding.SettingsNetworkFragmentBindingImpl;
                               ^
  symbol:   class SettingsNetworkFragmentBindingImpl
  location: package org.linphone.databinding
> Task :app:kaptDebugKotlin FAILED

> Task :app:kaptReleaseKotlin FAILED
/home/brian/linphone-android/app/build/generated/source/kapt/release/org/linphone/DataBinderMapperImpl.java:71: error: cannot find symbol
import org.linphone.databinding.ChatRoomMasterFragmentBindingImpl;
                               ^
  symbol:   class ChatRoomMasterFragmentBindingImpl
  location: package org.linphone.databinding/home/brian/linphone-android/app/build/generated/source/kapt/release/org/linphone/DataBinderMapperImpl.java:72: error: cannot find symbol
import org.linphone.databinding.ChatRoomMasterFragmentBindingLandImpl;
                               ^
  symbol:   class ChatRoomMasterFragmentBindingLandImpl
  location: package org.linphone.databinding/home/brian/linphone-android/app/build/generated/source/kapt/release/org/linphone/DataBinderMapperImpl.java:73: error: cannot find symbol
import org.linphone.databinding.ChatRoomMasterFragmentBindingSw533dpLandImpl;
                               ^
  symbol:   class ChatRoomMasterFragmentBindingSw533dpLandImpl
  location: package org.linphone.databinding/home/brian/linphone-android/app/build/generated/source/kapt/release/org/linphone/DataBinderMapperImpl.java:113: error: cannot find symbol
import org.linphone.databinding.SettingsNetworkFragmentBindingImpl;
                               ^
  symbol:   class SettingsNetworkFragmentBindingImpl
  location: package org.linphone.databinding
FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:validateSigningRelease'.
> Keystore file '/home/brian/linphone-android/app/bc-android.keystore' not found for signing config 'release'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:kaptReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 45s
55 actionable tasks: 16 executed, 39 up-to-date
```

**Comment by Viish** [comment]
Don't build as a release, you don't have our keystore to generate a release APK.

**Comment by brianjmurrell** [comment]
I just did the `./gradlew build --refresh-dependencies` you suggested above.  What should I do differently?

**Comment by Viish** [comment]
Yes

**Comment by brianjmurrell** [comment]
Cool.  Built and installed.  But trying to customise a bit...

```
> Task :app:kaptDebugKotlin FAILED
/home/brian/linphone-android/app/build/generated/source/kapt/debug/org/linphone/DataBinderMapperImpl.java:71: error: cannot find symbol
import org.linphone.databinding.ChatRoomMasterFragmentBindingImpl;
                               ^
  symbol:   class ChatRoomMasterFragmentBindingImpl
  location: package org.linphone.databinding/home/brian/linphone-android/app/build/generated/source/kapt/debug/org/linphone/DataBinderMapperImpl.java:72: error: cannot find symbol
import org.linphone.databinding.ChatRoomMasterFragmentBindingLandImpl;
                               ^
  symbol:   class ChatRoomMasterFragmentBindingLandImpl
  location: package org.linphone.databinding/home/brian/linphone-android/app/build/generated/source/kapt/debug/org/linphone/DataBinderMapperImpl.java:73: error: cannot find symbol
import org.linphone.databinding.ChatRoomMasterFragmentBindingSw533dpLandImpl;
                               ^
  symbol:   class ChatRoomMasterFragmentBindingSw533dpLandImpl
  location: package org.linphone.databinding/home/brian/linphone-android/app/build/generated/source/kapt/debug/org/linphone/DataBinderMapperImpl.java:113: error: cannot find symbol
import org.linphone.databinding.SettingsNetworkFragmentBindingImpl;
                               ^
  symbol:   class SettingsNetworkFragmentBindingImpl
  location: package org.linphone.databinding
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
30 actionable tasks: 8 executed, 22 up-to-date
```

From such a simple change:

```patch
--- a/app/src/main/res/values/strings.xml
+++ b/app/src/main/res/values/strings.xml
@@ -1,7 +1,7 @@
 <?xml version='1.0' encoding='UTF-8'?>
 
 <!DOCTYPE resources [
-    <!ENTITY appName "Linphone">
+    <!ENTITY appName "MyLinphone">
 ]>
 
 <resources>
```

I would think this sort of thing is the entire point of defining `appName`, no?

**Comment by Viish** [comment]
It's not your change. This build happens every other build or so, don't know why... Build again and it should be fine.

**Comment by brianjmurrell** [comment]
Haha.  You were right.  

So should this rewrite work with Google FCM exactly as master does?  I'm getting failures back from the push notification:

```
{"multicast_id":[redacted],"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"MismatchSenderId"}]}'
```

Not sure what `MismatchSenderId` is.

**Comment by Viish** [comment]
Actually it's now the SDK that handles the push, but it will still use the Google-services.json file in the app directory.
Did you forgot to replace it by yours?

**Comment by brianjmurrell** [comment]
No, didn't forget.  it's definitely mine.  In `app/google-services.json`.

**Comment by Viish** [comment]
Check the logs to see if the push information in the register (contact header) are OK

**Comment by brianjmurrell** [comment]
I'd see this same information in a SIP debug or in the contact record of the SIP server too wouldn't I?

Ultimately, given that most of that information is some kind of encoded/hashed value, what am I looking for exactly?

**Comment by Viish** [comment]
> I'd see this same information in a SIP debug or in the contact record of the SIP server too wouldn't I?

Yes.
Actually information isn't encoded or hashed. Look for the parameters in the contact uri. It will contain the push token but also the word firebase and the ID of the push project, it will be easy to see if it uses your Google-services.json or ours.

**Comment by brianjmurrell** [comment]
Looks like the app-id is wrong.

**Comment by brianjmurrell** [comment]
It's using 929724111839.  But I am looking at the `app/google-services.json` file right now and it has my app-id in it.  Is the SDK somehow not using the data from that file in the linphone project?

**Comment by Viish** [comment]
It shouldn't, the Sdk doesn't have our file.
Did you updated from a previous version that had our file?

**Comment by brianjmurrell** [comment]
I might have, but isn't the file part of the apk, such that if I build a new apk with a different file, it gets installed with the apk?  And I wouldn't have installed a _MyLinphone_ with your version of that file.

**Comment by Viish** [comment]
Can you upload the logs from the start of the app please?

**Comment by brianjmurrell** [comment]
There must be a file dependency missing in the build.  I had to [re-]move:

```
app/build/generated/res/google-services/debug/values/values.xml
app/build/intermediates/incremental/mergeDebugResources/merger.xml
app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
```

to get the correct app-id in the `Contact:` header.

**Comment by Viish** [comment]
Ok but you shouldn't have to do that.
Are you able to reproduce the issue? Because you didn't send me the logs I don't know what was causing the issue nor how I can fix it...

**Comment by brianjmurrell** [comment]
You don't need the logs.  I could see in the logs it was using your `app-id`, not mine.  I described exactly above what the problem is.  Of course I shouldn't have to remove those files by hand, the build system should be doing it by nature of seeing that the google-services.json file is newer.

You should be able to reproduce by simply changing the application ID in your google-services.json and rebuilding and noticing that it was not updated in the above files.

**Comment by Viish** [comment]
I think it was just cached files from previous build that was causing your issue.

**Comment by brianjmurrell** [comment]
What "cached" files?  Surely it's a bug if I update my `google-services.json` file and some kind of "cached" files prevent that update from making it into the package.

Did you try to reproduce as I described above?  Let's not let the supposition of "boogie men" stand in the way of rooting out a real bug.

**Comment by brianjmurrell** [comment]
I just tried the repro I described above and it reproduces.  I changed all of the instanced of my application id in `app/google-services.json` to `999` and then did `./gradlew installDebug` and then opened the app on the device and it still registered with my proper `app-id`.

**Comment by Viish** [comment]
Of course, installDebug only installs an existing APK file.
Do a `./gradlew assembleDebug` before and if the issue persists do a './gradlew clean' then assemble again and install.

**Comment by brianjmurrell** [comment]
I have always been able to use `installDebug` to both build and install a new APK if I change the source and the installed APK reflects my source changes.

**Comment by Viish** [comment]
It may build the sources again but not updating the resources.

**Comment by brianjmurrell** [comment]
And I can further confirm that once again, removing:

```
app/build/generated/res/google-services/debug/values/values.xml
app/build/intermediates/incremental/mergeDebugResources/merger.xml
app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
```

The new app used `app-id: 999`.

IMHO, `installDebug` really ought to operate like any build system's (i.e. `make`) `install` target where the build is a dependency of the install and every file that contributes to the build should be a dependency of the build such that `install` will always guarantee that what is installed is a reflection of it's ingredients.

**Comment by brianjmurrell** [comment]
`./gradlew assembleDebug; ./gradlew installDebug` doesn't fix it either.  Those 3 files still contain the `999` value.

Having to clean the entire tree just to update a resource such as this is a huge sledgehammer and should be considered a bug.  One should not have to rebuild every single file whose built value does not change because one updates one file that has no impact on the built file.

**Comment by Viish** [comment]
No but ./gradlew clean does fix it.
Feel free to tell google that their 'com.google.gms.google-services' plugin doesn't detect changes in the google-services.json file and that they could fix that.

**Comment by brianjmurrell** [comment]
Sure.  Any idea where they take bug reports for that?

**Comment by brianjmurrell** [comment]
https://github.com/google/play-services-plugins/issues/144 if you wish to expand or clarify any details.
