### ISSUE TITLE
Not waking screen up

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/linphone-android#1021]
As you know, I have feature/kotlin_rewrite installed on both my Nexus 5 running LineageOS 16.0 (Android 9.0) and my Huawei Honor 8 (Android 8.0).  I previously had release/4.3 and master installed on both devices.

On feature/kotlin_rewrite an incoming call:
- On my Nexus 5, rings, vibrates, etc. including turning the screen on.  All good.
- On my Honor 8, rings, vibrates, etc. except it does not turn the screen on.

On both master and release/4.3 an incoming call turned the screen on on both devices.

**Comment by Viish** [comment]
That's weird, so far I don't see any differences between the APIs called regarding that between the Java app and the Kotlin rewrite.

**Comment by Viish** [comment]
Actually my statement above isn't right, I don't know what version I compared...
Anyway this should fix it:
```
commit 1379493ac5d4dd6a280d6a0a17005da61083e9c6 (HEAD -> feature/kotlin_rewrite, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Mon May 25 13:48:01 2020 +0200

    Should fix screen not waked up on some devices
```

**Comment by brianjmurrell** [comment]
Unfortunately it didn't fix it.

Here's a [log](http://brian.interlinx.bc.ca/linphone-screen-doesnt-light.log) of receiving a call with no screen coming on.

**Comment by Viish** [comment]
For some reason it tries to start the MainActivity before the IncomingCallActivity. I guess that's why the activity isn't turning screen on (on my device only the IncomingCallActivity is started and screen works fine).

```
2020-05-25 09:35:11:731 [org.linphone.debug/liblinphone] MESSAGE Incoming call ringing for 0 seconds
2020-05-25 09:35:11:893 [org.linphone.debug/linphone-android] MESSAGE Activity started:org.linphone.activities.main.MainActivity@ef02a42
2020-05-25 09:35:11:896 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] Activity resumed:org.linphone.activities.main.MainActivity@ef02a42
2020-05-25 09:35:11:896 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] runningActivities=1
2020-05-25 09:35:11:896 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] App has left background mode
2020-05-25 09:35:11:896 [org.linphone.debug/linphone-android] MESSAGE [Core Manager] App has left background mode
2020-05-25 09:35:11:897 [org.linphone.debug/linphone-android] MESSAGE [Generic Activity] Device orientation is 0 (raw value is 0)
2020-05-25 09:35:11:918 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] Activity paused:org.linphone.activities.main.MainActivity@ef02a42
2020-05-25 09:35:11:919 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] runningActivities=0
2020-05-25 09:35:11:939 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] Activity created:org.linphone.activities.call.IncomingCallActivity@22fafd5
2020-05-25 09:35:12:001 [org.linphone.debug/linphone-android] MESSAGE [Call Incoming Decline Button] Slide mode is false
2020-05-25 09:35:12:004 [org.linphone.debug/linphone-android] MESSAGE [Call Incoming Decline Button] Slide mode is true
2020-05-25 09:35:12:004 [org.linphone.debug/linphone-android] MESSAGE [Permission Helper] Permission android.permission.RECORD_AUDIO is granted
2020-05-25 09:35:12:006 [org.linphone.debug/linphone-android] MESSAGE Activity started:org.linphone.activities.call.IncomingCallActivity@22fafd5
2020-05-25 09:35:12:013 [org.linphone.debug/liblinphone] MESSAGE Core callbacks [0x73d7324ec0] registered on core [0x73f689f400]
2020-05-25 09:35:12:013 [org.linphone.debug/liblinphone] MESSAGE Core callbacks [0x73d6ccc000] registered on core [0x73f689f400]
2020-05-25 09:35:12:020 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] Activity resumed:org.linphone.activities.call.IncomingCallActivity@22fafd5
2020-05-25 09:35:12:020 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] runningActivities=1
2020-05-25 09:35:12:021 [org.linphone.debug/linphone-android] MESSAGE [Generic Activity] Device orientation is 0 (raw value is 0)
2020-05-25 09:35:12:065 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] Activity paused:org.linphone.activities.call.IncomingCallActivity@22fafd5
2020-05-25 09:35:12:065 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] runningActivities=0
2020-05-25 09:35:12:081 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] Activity stopped:org.linphone.activities.main.MainActivity@ef02a42
2020-05-25 09:35:12:113 [org.linphone.debug/linphone-android] MESSAGE [Activity Monitor] Activity stopped:org.linphone.activities.call.IncomingCallActivity@22fafd5
```

**Comment by brianjmurrell** [comment]
Apologies.  I take back my previous report of the fix not working.  Forgot to rebase on latest feature/kotlin_rewrite.

**Comment by brianjmurrell** [comment]
I have to take back my _take-back_.  :frowning: I am now most certainly based on 6457874d7 and now both my Honor 8 and my Nexus 5 (running Pie) don't always light the screen up on an incoming call.  It seems intermittent though.  Here's a [log](linphone-doesnt-always-light-screen.txt) of my Honor 8 lighting up the screen for the first call but not lighting it up for the second after I put the phone to sleep with the power button.

**Comment by Viish** [comment]
Your log link doesn't work

**Comment by brianjmurrell** [comment]
Apologies.  Forgot to put the site path in front of the file path.  The comment with the log link has been updated.

**Comment by Viish** [comment]
Can you try with
```
commit b4f3697550c730e74fb2b81a71e700944ed91daa (HEAD -> feature/kotlin_rewrite, origin/feature/kotlin_rewrite)
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Tue May 26 20:50:14 2020 +0200

    Trying to prevent or understand issues with incoming call activity
```

**Comment by brianjmurrell** [comment]
On latest kotlin_rewrite (0fa49191b) and still having this problem, just FYI.

**Comment by killerbees19** [comment]
Same issue here with Linphone v4.6.7 (from F-Droid) at my Wileyfox Swift ("crackling") devices. I'm using self-compiled LineageOS 16.0 builds. Never had such issues with the old (non-Kotlin; v4.4) releases at this specific device.

**Comment by Viish** [comment]
@killerbees19 Can you try with linphone-android master branch please?

**Comment by killerbees19** [comment]
I'll try it next week. 🙂

(Currently too busy.)

**Comment by Viish** [comment]
Thanks! As a remainder, if it's easier, we upload nightly build APKs there: https://download.linphone.org/snapshots/android/

**Comment by killerbees19** [comment]
> @killerbees19 did you got the opportunity to test latest master?

Not yet, sorry! 😳

(And I've missed your previous link too.)

**Comment by killerbees19** [comment]
Sorry for my late response 😞

Clean test device with LineageOS 16.1 and…

* `linphone-android-debug-4.6.9.3+7b98cb738.apk`: Bug reproducible.
* `linphone-android-debug-4.7.0-alpha.224+9e20134b1.apk`: Bug fixed!

**Comment by Viish** [comment]
Thanks @killerbees19 !

**Comment by Viish** [comment]
I've applied the same fix on release/4.6 branch so 4.6.10 release will have it as well.

**Comment by Viish** [comment]
4.6.10 release has been published.

**Comment by killerbees19** [comment]
Confirmed, fixed in 4.6.10. 👍

Thank you very much! 🥳
