### ISSUE TITLE
Push notifications disable with remote provisioning

### ISSUE THREAD

**Issue by filmen** [BelledonneCommunications/linphone-android#1491]
Hello,
when I do the provisioning by QR-code, in SIP accounts settings, the option "Allow push notifications" is hidden and the push notifications doesn't work. In my provisioning file, in the context "proxy_0", I created an option:
`<entry name="push_notification_allowed">1</entry> `

1. Launch the app
2. Tap on "Fetch remote configuration"
3. Tap on "QRCODE" 
4. Tap on "Fetch and Apply"
5. After the configuration, go to SIP ACCOUNTS and scroll to "Allow Push Notifications" section.

If I try the manual configuration of SIP account, the push notifications works fine.

 - Device: Xiaomi MI A2 Lite
 - OS: Android 10
 - Lastest (master)
 - Lastest (master)

**Adb logcat logs**
2021-08-31 16:26:24.542 3662-3662/com.****.debug I/Linphone: Couldn't compute push notifications parameters on account [0x7200e31b88] because account params do not have available push notifications

2021-08-31 16:26:24.998 3662-3662/com.****.debug I/Linphone: [Core Manager] Push notification app id is [859727746867] and token is [f6C3Wvo5SHWVi790R_flem:APA91bEXodb9U4RsFt9BtwJ2UvxdytAiab_uNI5WUyk3V6pE-TAZace_as95Z2kP9nwF_dWsN3pNXNXoaW8WrhiSTXYFDDzXFoUYhbl3drGS5xNTnVHagJ9necB1Ip59tfHH8YkpohnU]
2021-08-31 16:26:24.999 3662-3662/com.****.debug I/Linphone: Push notifications parameters on account [0x7200e31b88] successfully computed : pn-type=firebase;app-id=859727746867;pn-tok=f6C3Wvo5SHWVi790R_flem:APA91bEXodb9U4RsFt9BtwJ2UvxdytAiab_uNI5WUyk3V6pE-TAZace_as95Z2kP9nwF_dWsN3pNXNXoaW8WrhiSTXYFDDzXFoUYhbl3drGS5xNTnVHagJ9necB1Ip59tfHH8YkpohnU;pn-timeout=0;pn-silent=1

2021-08-31 16:26:24.999 3662-3662/com.****.debug I/Linphone: Push notification information [pn-type=firebase;app-id=859727746867;pn-tok=f6C3Wvo5SHWVi790R_flem:APA91bEXodb9U4RsFt9BtwJ2UvxdytAiab_uNI5WUyk3V6pE-TAZace_as95Z2kP9nwF_dWsN3pNXNXoaW8WrhiSTXYFDDzXFoUYhbl3drGS5xNTnVHagJ9necB1Ip59tfHH8YkpohnU;pn-timeout=0;pn-silent=1] added to account [0x7200e31b88]

2021-08-31 16:26:24.999 3662-3662/com.****.debug I/Linphone: Push notification information updated: param [859727746867], prid [f6C3Wvo5SHWVi790R_flem:APA91bEXodb9U4RsFt9BtwJ2UvxdytAiab_uNI5WUyk3V6pE-TAZace_as95Z2kP9nwF_dWsN3pNXNXoaW8WrhiSTXYFDDzXFoUYhbl3drGS5xNTnVHagJ9necB1Ip59tfHH8YkpohnU]

2021-08-31 16:26:26.235 3662-3662/com.****.debug I/Linphone: ====> params.pushNotificationAllowed true
2021-08-31 16:26:26.235 3662-3662/com.****.debug I/Linphone: ====> core.isPushNotificationAvailable true
2021-08-31 16:26:26.346 3662-3662/com.****.debug I/Linphone:     <entry name="push_notification_allowed" overwrite="true">1</entry>

2021-08-31 16:26:26.347 3662-3662/com.****.debug I/Linphone: Set proxy_0|push_notification_allowed = 1
2021-08-31 16:26:26.367 3662-3662/com.****.debug I/Linphone: Couldn't compute push notifications parameters on account [0x71fc70dc88] because account params do not have available push notifications

2021-08-31 16:26:26.397 3662-3662/com.****.debug I/Linphone: ====> params.pushNotificationAllowed true
2021-08-31 16:26:26.397 3662-3662/com.****.debug I/Linphone: ====> core.isPushNotificationAvailable false

Thanks in advice for the answer.

**Comment by Viish** [comment]
What version of the SDK are you using?

**Comment by filmen** [comment]
I build the SDK following the instructions in GitHub page (https://github.com/BelledonneCommunications/linphone-sdk) so I think is the 5.1.0-alpha.35+504b631 version.

**Comment by Viish** [comment]
Ok because we fixed that issue in SDK 5.1.0-alpha.41.

**Comment by filmen** [comment]
Excuse me, but I have download the last version of project and the last version of SDK (5.1.0-alpha.43) and I compile them, but the issue still persist. 
Maybe the provisiong file is wrong? Could you share to me a sample XML file for remote provisioning, please?
Thanks.

**Comment by Viish** [comment]
> Excuse me, but I have download the last version of project and the last version of SDK (5.1.0-alpha.43) and I compile them, but the issue still persist.

Can you attach debug logs please?

> Could you share to me a sample XML file for remote provisioning, please?

A sample is available here: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/

**Comment by filmen** [comment]
Thanks for the answer.
Here is the logcat of ADB when I did "Fetch and Apply":

2021-09-01 15:50:27.176 2144-2144/#######.debug I/Linphone: Set proxy_0|reg_proxy = sip:fmenci-vpbx-dev-pjsip.centralino-cloud.it:5062
2021-09-01 15:50:27.176 2144-2144/#######.debug I/Linphone: Set proxy_0|reg_route = sip:fmenci-vpbx-dev-pjsip.centralino-cloud.it:5062
2021-09-01 15:50:27.176 2144-2144/#######.debug I/Linphone: Set proxy_0|reg_identity = sip:100@vpbx.test:5062
2021-09-01 15:50:27.176 2144-2144/#######.debug I/Linphone: Set proxy_0|reg_expires = 3600
2021-09-01 15:50:27.176 2144-2144/#######.debug I/Linphone: Set proxy_0|reg_sendregister = 1
2021-09-01 15:50:27.176 2144-2144/#######.debug I/Linphone: Set proxy_0|publish = 0
2021-09-01 15:50:27.176 2144-2144/#######.debug I/Linphone: Set proxy_0|dial_escape_plus = 0
2021-09-01 15:50:27.176 2144-2144/#######.debug I/Linphone: Set proxy_0|background_mode = 0
2021-09-01 15:50:27.176 2144-2144/#######.debug I/Linphone: Set proxy_0|push_notification_allowed = 1
2021-09-01 15:50:27.176 2144-2144/#######.debug I/Linphone: Set auth_info_0|username = 100
2021-09-01 15:50:27.176 2144-2144/#######.debug I/Linphone: Set auth_info_0|passwd = johndoe
2021-09-01 15:50:27.177 2144-2144/#######.debug I/Linphone: Set auth_info_0|realm = asterisk
2021-09-01 15:50:27.177 2144-2144/#######.debug I/Linphone: Set assistant|domain = 
2021-09-01 15:50:27.177 2144-2144/#######.debug I/Linphone: Set assistant|algorithm = MD5
2021-09-01 15:50:27.177 2144-2144/#######.debug I/Linphone: Set assistant|password_max_length = -1
2021-09-01 15:50:27.177 2144-2144/#######.debug I/Linphone: Set assistant|password_min_length = 0
2021-09-01 15:50:27.177 2144-2144/#######.debug I/Linphone: Set assistant|username_length = -1
2021-09-01 15:50:27.177 2144-2144/#######.debug I/Linphone: Set assistant|username_max_length = 128
2021-09-01 15:50:27.177 2144-2144/#######.debug I/Linphone: Set assistant|username_min_length = 1
2021-09-01 15:50:27.177 2144-2144/#######.debug I/Linphone: Set assistant|username_regex = ^[a-zA-Z0-9+_.\-]*$
2021-09-01 15:50:27.179 2144-2144/#######.debug I/Linphone: Reading config information from /data/user/0/#######.debug/files/linphonerc
2021-09-01 15:50:27.186 2144-2144/#######.debug I/Linphone: This device (Xiaomi/Mi A2 Lite/msm8953) declares it has a built-in echo canceller.
2021-09-01 15:50:27.186 2144-2144/#######.debug I/Linphone: No information available for [Xiaomi/Mi A2 Lite/msm8953],
2021-09-01 15:50:27.186 2144-2144/#######.debug I/Linphone: Using android >= 8 sound device descriptor.
2021-09-01 15:50:27.186 2144-2144/#######.debug I/Linphone: Sound device information for [Xiaomi/Mi A2 Lite/msm8953] is: builtin=[yes], delay=[0] ms
2021-09-01 15:50:27.204 2144-2144/#######.debug I/Linphone: Linphone core [0x7d836c1800] notified [configuring_status]
2021-09-01 15:50:27.204 2144-2144/#######.debug I/Linphone: Found Android plugin libmsandroidcamera2.so
2021-09-01 15:50:27.204 2144-2144/#######.debug I/Linphone: Found Android plugin libmswebrtc.so
2021-09-01 15:50:27.204 2144-2144/#######.debug I/Linphone: Found Android plugin libmsaaudio.so
2021-09-01 15:50:27.204 2144-2144/#######.debug I/Linphone: Loading ms plugins from list
2021-09-01 15:50:27.204 2144-2144/#######.debug I/Linphone: Loading plugin libmsandroidcamera2.so...
2021-09-01 15:50:27.205 2144-2144/#######.debug I/Linphone: [Camera2 Capture] libmsandroidcamera2 plugin loaded
2021-09-01 15:50:27.205 2144-2144/#######.debug I/Linphone: Plugin loaded (libmsandroidcamera2.so)
2021-09-01 15:50:27.205 2144-2144/#######.debug I/Linphone: Loading plugin libmswebrtc.so...
2021-09-01 15:50:27.206 2144-2144/#######.debug I/Linphone: libmswebrtc 1.1.1 plugin loaded, iSAC codec version 3.6.0, iLBC codec version 1.1.1
2021-09-01 15:50:27.206 2144-2144/#######.debug I/Linphone: Plugin loaded (libmswebrtc.so)
2021-09-01 15:50:27.206 2144-2144/#######.debug I/Linphone: Loading plugin libmsaaudio.so...
2021-09-01 15:50:27.206 2144-2144/#######.debug I/Linphone: [AAudio] libmsaaudio plugin loaded
2021-09-01 15:50:27.206 2144-2144/#######.debug I/Linphone: [Android Audio Utils] Using 48000 for sample rate value
2021-09-01 15:50:27.206 2144-2144/#######.debug I/Linphone: [AAudio] libaaudio.so successfully loaded
2021-09-01 15:50:27.214 2144-2144/#######.debug I/Linphone: This device (Xiaomi/Mi A2 Lite/msm8953) declares it has a built-in echo canceller.
2021-09-01 15:50:27.214 2144-2144/#######.debug I/Linphone: No information available for [Xiaomi/Mi A2 Lite/msm8953],
2021-09-01 15:50:27.214 2144-2144/#######.debug I/Linphone: Using android >= 8 sound device descriptor.
2021-09-01 15:50:27.214 2144-2144/#######.debug I/Linphone: Sound device information for [Xiaomi/Mi A2 Lite/msm8953] is: builtin=[yes], delay=[0] ms
2021-09-01 15:50:27.214 2144-2144/#######.debug I/Linphone: [AAudio] Soundcard created
2021-09-01 15:50:27.214 2144-2144/#######.debug I/Linphone: Plugin loaded (libmsaaudio.so)
2021-09-01 15:50:27.214 2144-2144/#######.debug I/Linphone: All plugins in list correctly loaded
2021-09-01 15:50:27.214 2144-2144/#######.debug W/Linphone: Device [Android Sound card] type is unknown
2021-09-01 15:50:27.215 2144-2144/#######.debug I/Linphone: Linphone core [0x7d836c1800] notified [audio_devices_list_updated]
2021-09-01 15:50:27.215 2144-2144/#######.debug I/Linphone: linphone_core_set_playback_gain_db(): no active call.
2021-09-01 15:50:27.215 2144-2144/#######.debug I/Linphone: linphone_core_set_mic_gain_db(): no active call.
2021-09-01 15:50:27.215 2144-2144/#######.debug I/Linphone: Sal nat helper [enabled]
2021-09-01 15:50:27.215 2144-2144/#######.debug I/Linphone: Sal use rports [enabled]
2021-09-01 15:50:27.217 2144-2144/#######.debug I/Linphone: MTU is supposed to be 1300, rtp payload max size will be 1240
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for SILK
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for AMR
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for AMR-WB
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for G729
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for mpeg4-generic
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for mpeg4-generic
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for SILK
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for SILK
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for G726-16
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for G726-24
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for G726-32
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for G726-40
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for AAL2-G726-16
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for AAL2-G726-24
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for AAL2-G726-32
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for AAL2-G726-40
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for CODEC2
2021-09-01 15:50:27.218 2144-2144/#######.debug I/Linphone: Could not find encoder for BV16
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Could not find encoder for 1016
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Could not find encoder for G723
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Could not find encoder for LPC
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Could not find encoder for CN
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Could not find encoder for MP4V-ES
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Could not find encoder for H263-1998
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Could not find encoder for H263
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Could not find encoder for H261
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Could not find encoder for MPV
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Supported codec red/1000 fmtp= automatically added to codec list.
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Supported codec t140/1000 fmtp= automatically added to codec list.
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Sal use rports [enabled]
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: belle_sip_stack_set_well_know_port() : set to [5060]
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: belle_sip_stack_set_well_know_port_tls() : set to [5061]
2021-09-01 15:50:27.219 2144-2144/#######.debug I/Linphone: Root ca path set to /data/user/0/#######.debug/files/share/linphone/rootca.pem
2021-09-01 15:50:27.225 2144-2144/#######.debug W/Linphone: generated proxyconfig idkey = [proxy_config_XyyhHuGMVzlFPfQ]
2021-09-01 15:50:27.225 2144-2144/#######.debug I/Linphone: LinphoneAccount[0x7d2d444848] created with params
2021-09-01 15:50:27.225 2144-2144/#######.debug I/Linphone: LinphoneAccount[0x7d2d444848] created with proxy config
2021-09-01 15:50:27.225 2144-2144/#######.debug I/Linphone: linphoneAccountIsServerConfigChanged : 0
2021-09-01 15:50:27.225 2144-2144/#######.debug I/Linphone: Publish params have changed on account [0x7d2d444848]
2021-09-01 15:50:27.226 2144-2144/#######.debug I/Linphone: Invalidating friends maps for list [0x7d836f13a0]
2021-09-01 15:50:27.226 2144-2144/#######.debug I/Linphone: Sal::unlistenPorts(): done
2021-09-01 15:50:27.227 2144-2144/#######.debug I/Linphone: Creating listening point [0x7d84624400] on [sip:[::0]:-1;transport=UDP]
2021-09-01 15:50:27.227 2144-2144/#######.debug I/Linphone: Random UDP port is 45465
2021-09-01 15:50:27.227 2144-2144/#######.debug I/Linphone: Creating listening point [0x7d2d416100] on [sip:[::0]:-1;transport=TCP]
2021-09-01 15:50:27.227 2144-2144/#######.debug I/Linphone: Random TCP port is 38032
2021-09-01 15:50:27.227 2144-2144/#######.debug I/Linphone: Creating listening point [0x7d2d416180] on [sip:[::0]:-1;transport=TLS]
2021-09-01 15:50:27.227 2144-2144/#######.debug I/Linphone: Random TCP port is 40869
2021-09-01 15:50:27.228 2144-2144/#######.debug I/Linphone: Root ca path set to /system/etc/security/cacerts
2021-09-01 15:50:27.228 2144-2144/#######.debug I/Linphone: Root ca path set to /system/etc/security/cacerts
2021-09-01 15:50:27.228 2144-2144/#######.debug I/Linphone: Root ca path set to /data/user/0/#######.debug/files/share/linphone/rootca.pem
2021-09-01 15:50:27.230 2144-2144/#######.debug I/Linphone: [Context] Global state changed [On]
2021-09-01 15:50:27.230 2144-2144/#######.debug W/Linphone: [Contacts Manager] Cancelling existing async task
2021-09-01 15:50:27.230 2144-2144/#######.debug I/Linphone: [Contacts Loader] Synchronization started
2021-09-01 15:50:27.231 2144-2144/#######.debug I/Linphone: Linphone core [0x7d836c1800] notified [global_state_changed]
2021-09-01 15:50:27.231 2144-2681/#######.debug I/Linphone: [Contacts Loader] Background synchronization started
2021-09-01 15:50:27.231 2144-2144/#######.debug I/Linphone: channel [0x7d2e1da500]: ending recv background task with id=[27ea].
2021-09-01 15:50:27.232 2144-2144/#######.debug I/Linphone: bellesip_wake_lock_release(): Android wake lock released [ref=0x27ea]
2021-09-01 15:50:27.232 2144-2144/#######.debug I/Linphone: LinphoneAccount [0x7d2d444840] about to register (LinphoneCore version: 5.1.0-alpha-48-g152a07fd4)
2021-09-01 15:50:27.236 2144-2144/#######.debug E/Linphone: Couldn't compute automatic push notifications parameters on account [0x7d2d444848] because account params do not have available push notifications

**Comment by Viish** [comment]
Please attach logs from the start of the app.

**Comment by filmen** [comment]
Ok, sorry.
Here it is. 
[logcat-adb-app.txt](https://github.com/BelledonneCommunications/linphone-android/files/7091888/logcat-adb-app.txt)

**Comment by Viish** [comment]
Thanks!

**Comment by Viish** [comment]
Please try with SDK 5.1.0-alpha.50+724b895

**Comment by filmen** [comment]
Ok. Thanks.
Yesterday I compiled the app with SDK 5.1.0-alpha.49 and in that version, push notification was visible with remote provisioning and works fine. Anyway I'll compile a new version with 5.1.0-alpha.50. I'll let you know.

**Comment by Viish** [comment]
Ok then don't bother, SDK 50 was the pre-built from last night but fix was actually in 5.1.0-alpha.48
