### ISSUE TITLE
Low volume for remote party when using TelecomManager

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#1574]
**Describe the bug**
When "Improve interactions with bluetooth devices" is enabled and a call is made, the volume on both sides is usually fine. Then, quit Linphone, open it again and make the same call: the remote party experiences low volume sound. It appears that the microphone volume from Linphone has lowered significantly.
When force stopping Linphone, the volume has restored back to normal.

**If the issue is about the SDK (build, issue, etc...) open the ticket in the [linphone-sdk](https://github.com/BelledonneCommunications/linphone-sdk) repository or one of it's submodules!**

**To Reproduce**

**Expected behavior**

**Please complete the following information**
 - Device: Samsung Galaxy S10e
 - OS: Android 11
 - Version of the App 4.6.0-beta.42+55757a107
 - Version of the SDK 5.1.0-beta.19+053bab1

**SDK logs**
Enable debug logs in advanced section of the settings, restart the app, reproduce the issue and then go to About page, click on "Send logs" and copy/paste the link here.

[61b9ef71729f2_f1c9c9f94cd981472f6b.txt](https://github.com/BelledonneCommunications/linphone-android/files/7719852/61b9ef71729f2_f1c9c9f94cd981472f6b.txt)

**Adb logcat logs**
In case of a crash of the app, please also provide the stack trace of the crash using adb logcat.

**Screenshots**

**Additional context**

**Comment by Viish** [comment]
Sorry but I don't understand.
In your logs the first call is without Telecom Manager, the second is with Telecom Manager and the last one is without.
Is the problem with or without it?

**Comment by driesken** [comment]
Sorry, it only occurs when the Telecom Manager is enabled.

I've generated some new logs where I've done the following:

- Make call with 21208, received volume is OK
- Make second call with 21208, received volume is still OK
- Quit Linphone
- Make third call with 21208, received volume is too low

[61b9f803ad3ac_3548c192aa8af7ef351f.txt](https://github.com/BelledonneCommunications/linphone-android/files/7720066/61b9f803ad3ac_3548c192aa8af7ef351f.txt)
.

**Comment by driesken** [comment]
This behavior is also present on a Samsung Galaxy S20 FE. If you're interested, I can also generate some logs on that device.

**Comment by Viish** [comment]
Can you try by changing default input & output audio devices in Audio settings to use OpenSLES mic & earpiece instead of AAudio ones?

**Comment by driesken** [comment]
Already tried that, but same problem. I've done the following:

- Modified both to OpenSLES. Quit Linphone, clear logs.
- Make call with 21208, received volume is OK
- Quit Linphone
- Make another call with 21208, received volume is too low

[61bb358db8956_adec47815e51af688e75.txt](https://github.com/BelledonneCommunications/linphone-android/files/7727388/61bb358db8956_adec47815e51af688e75.txt)

**Comment by Viish** [comment]
Can you confirm that the call with "low volume" in your log file is the one with ID "BSk9qGoREp" ?

**Comment by driesken** [comment]
That's right, the last call in the log.

**Comment by Viish** [comment]
Ok I think I know what happens.
It seems when you quit & start Linphone again, Telecom Helper isn't created.
I've pushed a potential fix for it in release/4.6, could you try it?

**Comment by driesken** [comment]
I've applied the potential fix on my local master branch (I'm not on 4.6 yet) but unfortunately it didn't fix the issue (same as in official beta version).

For both calls I get:
`MESSAGE [Context] Telecom Helper created, account is enabled`

**Comment by driesken** [comment]
Sorry, forgot to attach them earlier.

[61c081eb0f467_03859693cfe4044abbd1.txt](https://github.com/BelledonneCommunications/linphone-android/files/7745680/61c081eb0f467_03859693cfe4044abbd1.txt)

**Comment by Viish** [comment]
Thanks.
Can you try to cherry-pick commit `e9266dc0` please?

**Comment by driesken** [comment]
Yes, that one fixed it! Thanks again for your tremendous effort.

**Comment by Viish** [comment]
You're welcome!
