### ISSUE TITLE
4.6.0 crash on Android 9 after pick up calls then do sth

### ISSUE THREAD

**Issue by basncy** [BelledonneCommunications/linphone-android#1604]
**Describe the bug**
4.6.0 crash on Android 9 after pick up calls then do sth

**To Reproduce**
1. Login an account, linphone account or sip account.
2. call this account from another device.
3. pick up calls.
4. enable video from caller, or enable hands-free(Speaker). 

FIY:
4.5.6 on Android 9 works well.
4.6.0 on Android 10 works well.

https://www.linphone.org:444//tmp/6205353687868_b990291f4c8c325d4da7.gz

**Comment by Viish** [comment]
Hi,

Thanks for the bug report.
Can you try to reproduce this issue without the headset plugged in your phone?
Also can you attach the stack trace from adb logcat please?

Thanks in advance.

**Comment by basncy** [comment]
Always happen even nothing plugin my phone.
BTW, I saw a difference from 4.5.6 when picking up calls from the screen off, it requires me to unlock my screen when doing step 4.

What's the adb command to execute to get what you want?

**Comment by Viish** [comment]
> it requires me to unlock my screen when doing step 4.

Can you make me a video please?

> What's the adb command to execute to get what you want?

`adb logcat`

**Comment by basncy** [comment]
Please download from here.
http://129.146.185.197:8880/d/CrashLogs-4.6.0.zip

**Comment by Viish** [comment]
Thanks for the logs.

> it requires me to unlock my screen when doing step 4.

It simply because app crashes, thus the call view that has the rights to be above lock screen is gone.

Regarding your crash, can you tell me on which Android OS you are? I guess not the Samsung default firmware?

**Comment by basncy** [comment]
> Regarding your crash, can you tell me on which Android OS you are? I guess not the Samsung default firmware?

N9500ZCU7DUC1 with root.

**Comment by Viish** [comment]
That what I suspected. I guess custom roms don't behave well with TelecomManager APIs...

I fixed the crash but until 4.6.1 is released you can disable the "Improve interactions with bluetooth devices" setting in "Call" section, it should prevent the crash.

**Comment by basncy** [comment]
>  disable the "Improve interactions with bluetooth devices" setting in "Call" section, it should prevent the crash.

This fixes this crash issue, thanks Viish.

**Comment by basncy** [comment]
@Viish Still crashes in 4.6.1 if I enable Speaker BEFORE hearing the ring tone.

**Comment by Viish** [comment]
> Still crashes in 4.6.1 if I enable Speaker BEFORE hearing the ring tone.

Thanks, I'll take a look at it tomorrow.

**Comment by Viish** [comment]
Hi @basncy,

> Still crashes in 4.6.1 if I enable Speaker BEFORE hearing the ring tone.

This issue should be fixed in release/4.6 branch now.
