### ISSUE TITLE
Error when running Makefile script

### ISSUE THREAD

**Issue by rmigal** [BelledonneCommunications/linphone-android#191]
Hello everyone. I'm trying to build this project.
Run prepare.py and after that running "make" and getting this error after few minutes
```
[ 82%] Forcing build for 'EP_belr'
[ 82%] Performing build step for 'EP_belr'
[ 66%] Built target belr-static
[ 77%] Linking CXX executable belr_tester
/Users/username/Downloads/android-ndk-r15c/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: liblog.so, needed by /Users/username/Projects/linphone-android/liblinphone-sdk/android-arm64/lib/libbctoolbox-tester.so, not found (try using -rpath or -rpath-link)
/Users/username/Projects/linphone-android/liblinphone-sdk/android-arm64/lib/libbctoolbox-tester.so: undefined reference to `__android_log_vprint'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[6]: *** [tester/belr_tester] Error 1
make[5]: *** [tester/CMakeFiles/belr_tester.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/username/Projects/linphone-android/WORK/android-arm64/Stamp/EP_belr/EP_belr-build] Error 2
make[2]: *** [CMakeFiles/EP_belr.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [arm64-build] Error 2
```
Android NDK r15c is installed and path is set. The same issue with the ndk r11c.
My OS is macOS High Sierra.
Does anyone know what's going on?

**Comment by Ssisyphus** [comment]
Have you solved the problem? so do I, but my os is ubuntu.

**Comment by ejo4041** [comment]
I'm having the same issue with belr_tester, on the recommended Debian.

**Comment by ejo4041** [comment]
So I think I got past this error by reverting the last commit from Simon:
commit 61244560df5f4f45a495d8525e970aa73e4e3beb

To fix that, I did:
git reset HEAD~

Then did ./prepare.py -c
./prepare.py
make

But now I have a new error:
[ 15%] Building C object src/CMakeFiles/mediastreamer_voip.dir/crypto/zrtp.c.o
/home/linphone-android/submodules/mediastreamer2/src/crypto/zrtp.c:71:8: error: use of undeclared identifier 'ZRTP_KEYAGREEMENT_X255'; did you mean 'MS_ZRTP_KEY_AGREEMENT_X255'?
                case(ZRTP_KEYAGREEMENT_X255): return "ECDH-255";
                     ^~~~~~~~~~~~~~~~~~~~~~
                     MS_ZRTP_KEY_AGREEMENT_X255

**Comment by rmigal** [comment]
@Ssisyphus I have the same issue on the ubuntu too. From which branch you try to build?

**Comment by Ssisyphus** [comment]
@rmigal The master branch

**Comment by rmigal** [comment]
@Ssisyphus did you manage to solve the problem? If yes, can you explain me how you did it. Thanks

**Comment by Ssisyphus** [comment]
No, I'm stumped by this problem

**Comment by rmigal** [comment]
@ejo4041 Can you leave a link to the commit to which you returned. Thanks

**Comment by rmigal** [comment]
@Ssisyphus Hi dude. I have fixed this problem.
I just switched to this commit: https://github.com/BelledonneCommunications/linphone-android/commit/c7186b6313d12f4c030800cec11a7234a50feaba
then ./prepare.py
and make

**Comment by ejo4041** [comment]
@rmigal I tried checking out that commit, but I am still seeing the ZRTP_KEYAGREEMENT_X255 error I posted earlier.  Did you get past that or make any changes besides checking out that commit?

**Comment by rmigal** [comment]
@ejo4041 I deleted the folder. Cloned repo again, then downloaded the submodules and checked out to c7186b6
