### ISSUE TITLE
Duplicate accounts when using provisioning xml.

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-android#348]
In Linphone 4.0.1, after every Linphone restart a duplicate account is created when the account was set up by a provisioning xml. 

As a workaround, I had to (re)move the xml remotely from the webserver. Can this be fixed?

**Comment by Viish** [comment]
It should already be fixed by commit 5f5bd423941cc1a13bfb7f3fe79e12631b8af85d in linphone's repository

**Comment by lmm-git** [comment]
Yeah I think the problem is that the current version of the app in the google play store still has this error. Took me a little while to figure this out. When compiling the app (on master) by myself it is fixed.

Is it possible to update the google play store version of the app in near future?

**Comment by S0U1SB4N3** [comment]
verified.... error still exists in all builds for Linphone-android 3/18/19
