### ISSUE TITLE
LinphoneActivity loop on Oreo when screen is locked and call is missed

### ISSUE THREAD

**Issue by czaviar** [BelledonneCommunications/linphone-android#500]
Hi,

I noticed a loop, which results in a dozen of REGISTER commands per second! and quick battery drain. The loop appers on these conditions:
- Oreo 8.1 with Linphone 4.0.1
- Screen lock is set (no mather if swipe, PIN, etc.)
- The screen is off and the incomming call is being performed
- if I do not answer this call (missed call) the LinphoneActivity starts throwing the following errors:

Activity reported stop, but no longer stopping: ActivityRecord{87fbe0b u0 org.linphone/.activities.LinphoneActivity t39}
2019-03-08 15:43:00.356 21429-21429/org.linphone E/ActivityThread: Performing stop of activity that is already stopped: {org.linphone/org.linphone.activities.LinphoneActivity}
    java.lang.RuntimeException: Performing stop of activity that is already stopped: {org.linphone/org.linphone.activities.LinphoneActivity}
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3997)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4085)
        at android.app.ActivityThread.-wrap24(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6497)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

an then a loop of:

21429-21429/org.linphone E/ActivityThread: ActivityClientRecord{paused=true, stopped=true, hideForNow=false, startsNotResumed=false, isForward=true, pendingConfigChanges=0, onlyLocalRequest=false, preserveWindow=false, Activity{resumed=false, stopped=true, finished=false, destroyed=false, startedActivity=false, temporaryPause=false, changingConfigurations=false}}
2019-03-08 15:43:00.359 1099-2065/? I/ActivityManager: START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.android.packageinstaller cmp=com.android.packageinstaller/.permission.ui.GrantPermissionsActivity (has extras)} from uid 10077
2019-03-08 15:43:00.360 741-741/? D/QCOM PowerHAL: LAUNCH HINT: ON
2019-03-08 15:43:00.360 741-741/? D/QCOM PowerHAL: Activity launch hint handled
2019-03-08 15:43:00.428 1099-2833/? I/ActivityManager: Activity reported stop, but no longer stopping: ActivityRecord{87fbe0b u0 org.linphone/.activities.LinphoneActivity t39}
2019-03-08 15:43:00.439 1099-2833/? I/ActivityManager: START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.android.packageinstaller cmp=com.android.packageinstaller/.permission.ui.GrantPermissionsActivity (has extras)} from uid 10077
2019-03-08 15:43:00.440 741-741/? D/QCOM PowerHAL: LAUNCH HINT: ON
2019-03-08 15:43:00.440 741-741/? D/QCOM PowerHAL: Activity launch hint handled
.
.
.
2019-03-08 15:43:00.440 741-741/? D/QCOM PowerHAL: LAUNCH HINT: ON
.
.
.

The loops stops once I unlock the screen and open the app.

If I do not use a screen lock the problem does not occur. It also used to work without any problems on Linphone 3.3.2.

[screen_lock_bug.txt](https://github.com/BelledonneCommunications/linphone-android/files/2946510/screen_lock_bug.txt)

**Comment by Viish** [comment]
Hi,
Thanks for the report, I do reproduce this issue even with the 4.1 dev branch.
I'll have that fixed before the release.
Best regards.

**Comment by Viish** [comment]
Fixed in 5ddc65371c3f5d253be51edb24713ef04f071ef9

**Comment by czaviar** [comment]
Thanks, but I still experience the issue with freshly downloaded 4.1 dev branch (with 5ddc653 fix). Logcat still shows the errors listed above. The only advantage is that it stopped sending tousands of REGISTERs to SIP server.
