### ISSUE TITLE
How to logout SIP account

### ISSUE THREAD

**Issue by nhoxbypass** [BelledonneCommunications/linphone-android#63]
I spent some times to research how to logout with SIP account. 
When i press "Delete account" from the Account Settings of Navigation Drawer menu, i saw the account status is "Registration failed", but i still can make a call to this account, it still show the IncomingCallActivity.
The only way i can do it now is check Disable checkbox, but that's not what i want. 
Can you show me how to completely "Log out" an account? Thanks.

**Comment by DatBewar** [comment]
Hello,
I fixed the bug on delete account with this commit:
b6bf0bb74eaebd82771ee1c9771b753f9a1f5aa6
Now it's doing what you want i think.

**Comment by alexiagonzalez** [comment]
Hi. Sorry, we know this issue is closed, but could it be possible that it still occurs?

We use Linphone as base for our project. We've noticed that calls continue being received during a few minutes in our app after performing a logout ( = removing all accounts/proxies/authinfo, and following previous advices, etc) in certain circumstances. (We just only allow an account in our app)

We've detected that issue at Linphone app too... Is it really fixed at Linphone app? or do you know any specific commit where the issue was resolved for Linphone or any link we can follow?

Maybe the server (we use Freeswitch) should be who must unregister the user after a logout communication from app, cause the app couldn't do it?

We have detected this issue in our app in iOS and Android platform. We haven't found any solution for this issue in our app, however at least In iOS we have partially fixed its consequences, but the same is harder in Android.

Any help would be very appreciated. Thanks in advance, and very good work.

**Comment by HolyWon** [comment]
Hi, we have the same issue. test case as below.

Precondition:
Two phones. Three accounts: Account A B and C
Login with account A on the first phone,
Login with account C on the second phone.

Steps:
Logout the account A from the first phone;
Login with account B on the first phone;
Make a call from account C to Account A;

Result:
The first phone will receive the call;

**Comment by haohoangtran** [comment]
same with me

**Comment by Viish** [comment]
SDK issue, not Android

**Comment by jameshieuhc741** [comment]
Hello, i do remove account by 
core.removeProxyConfig(mProxyConfig);
core.removeAuthInfo(mAuth);
but when I restart app so i also received incomming call to outside. 
Please help me? How to remove account and turn off notification when remove account!

**Comment by raviteja74** [comment]
this issue is not resolved still it getting call after logout the sip account Please check this once
