### ISSUE TITLE
audio route switche from bluetooth earphone with no reason

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-android#814]
Sometimes, when I make a call with bluetooth headset connected, it connects bluetooth headset sucessfully (it beeps twice as usual) and it starts a call with bluetooth route selected: I hear the other side, but then (within 1-3 seconds) it switches an audio route from bluetooth to earphone suddenly, with no reason. Bluetooth headset keeps attached: I can successfully switch the route (manually) and the headset will not beep twice, but just will work.

I have a logcat with such a moment captured, But it's hard to reduce it and I won't make it public available, could you say, how can I send it for you (e-mail will be ok)?

**Comment by Viish** [comment]
Yes send them by email to linphone-android@belledonne-communications.com please.

**Comment by 532910** [comment]
Sent.

**Comment by Viish** [comment]
I guess it has been fixed by commit 9a7baf96855b210b0e82f38015cf074d0cbdc987 because I don't reproduce it.

**Comment by 532910** [comment]
still see it in version 4.2.0-beta.66+4c468a70
log and scree record sent by e-mail

**Comment by Viish** [comment]
It is because of this log:
`[Headset] Headset disconnected:null`
When this happen we force the audio route to be earpiece, that explains the sudden change.
The real question is, why do your device sends a broadcast about a headset being disconnected...

**Comment by Viish** [comment]
Can you tell me if commit 267fe040e275c091450a498bdd72de049aba12a4 fixes it ?

**Comment by 532910** [comment]
Surely I'll check it as soon as the update become available, but I don't know how to reproduce it. Looks like it happens after driving a car. Usually I use Plantronics Edge that has two profiles (A2DP and headset), but the car has audio system with A2DP only. So I connect Edge with headset profile and car with A2DP profile. Moreover it reconnects many times as I leave car and come back.

I've just turned off bluetooth on the phone, turned off headset and quit linphone, switched on all again but the issue still present.

I see this issue only with linphone, native dialer and riot work fine.
