### ISSUE TITLE
Record on incoming call is broken

### ISSUE THREAD

**Issue by Diyou** [BelledonneCommunications/linphone-android#941]
I can record any call when making a call but when the client is called it works only the first time after starting the app. The record button is still clickable but does nothing after that.

**Comment by Viish** [comment]
Thanks for the report, I just fixed it in both master & release branches.

**Comment by mollusko** [comment]
I'm actually still experiencing this issue, version 4.2.3 for Android. Have tried force-stopping the app & rebooting device, still only able to record outgoing calls & unable to record incoming calls.

Thanks!

**Comment by Viish** [comment]
It was fixed after release 4.2.3. Use latest commit on release/4.2 branch or master.
Or use directly commit id 1920bd8875d59a2b321f94736c77f60a2cca6d3f for release/4.2 or 17049469223afcb30bddf51a71fdc2e639d671f9 for master.
